import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data

DEVICE = 'cuda'
SEED = 42


### Training parameters ###

TRAIN_POLARIZATION_FRACTION = 0.8
FEATURE_SET = 'burn_context'
NUM_BINS = 500
NUM_EPOCHS = 1000
BATCH_SIZE = 64
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
LR_PATIENCE = 5
PATIENCE = 50
MIN_DELTA = 1e-6
LR_FACTOR = 0.5
LR_MIN = 1e-8
MAX_GRAD_NORM = 1.0
HIDDEN_DIM = 256

def to_column(values: np.ndarray) -> torch.Tensor:
    return torch.from_numpy(values).float().reshape(-1, 1)

def to_matrix(values: np.ndarray) -> torch.Tensor:
    return torch.from_numpy(values).float()


class BinModel(nn.Module):

    def __init__(self, input_dim: int, hidden_dim: int = 128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim, bias=True),
            nn.ReLU(),
            #nn.BatchNorm1d(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim, bias=True),
            nn.ReLU(),
            #nn.BatchNorm1d(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim, bias=True),
            nn.ReLU(),
            #nn.BatchNorm1d(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim, bias=True),
            nn.ReLU(),
            #nn.BatchNorm1d(hidden_dim),
            nn.Linear(hidden_dim, 2, bias=True),
        )

        self._initialize_weights()

    def _initialize_weights(self) -> None:
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.constant_(module.bias, 0.0)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        out = self.net(x)
        return out[:, 0], out[:, 1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a single binning model for one bin index."
    )
    parser.add_argument("--bin-idx", 
        type=int, 
        required=True, 
        help="Target bin index")
    parser.add_argument(
        "--lookup-table",
        type=Path,
        default=Path("Data_Creation/burn_lookup_table.pkl"),
        help="Path to burn_lookup_table.pkl generated by burn_lookup_table.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("TensorStudies/single_bin_results_v2"),
        help="Directory for checkpoints and metrics",
    )
    return parser.parse_args()



def _column_at_burn_bin(values: pd.Series, target_bin: int) -> np.ndarray:
    sample = values.iloc[0]
    arr = np.asarray(sample)
    if arr.ndim == 0 or arr.size == 1:
        return values.to_numpy(dtype=np.float32)
    stacked = np.stack(values.values)
    return stacked[:, target_bin].astype(np.float32)


def load_burn_bin_arrays(
    lookup_path: Path,
    target_bin: int,
    train_polarization_fraction: float,
    feature_set: str,
) -> Dict[str, Any]:

    df = pd.read_pickle(lookup_path)

    subset = df[df["burn_bin_idx"] == target_bin].copy()

    iplus = _column_at_burn_bin(subset["Iplus"], target_bin)
    iminus = _column_at_burn_bin(subset["Iminus"], target_bin)

    ps = subset["ps_at_burn_bin"].to_numpy(dtype=np.float32)
    polarizations = subset["P"].to_numpy(dtype=np.float32)


    features = np.column_stack([ps, polarizations]).astype(np.float32)

    shuffled_polarizations = np.random.permutation(polarizations)
    train_mask = np.isin(polarizations, shuffled_polarizations[:int(round(len(shuffled_polarizations) * train_polarization_fraction))])
    holdout_mask = np.isin(polarizations, shuffled_polarizations[int(round(len(shuffled_polarizations) * train_polarization_fraction)):])


    return {
        "x_train": to_matrix(features[train_mask]),
        "iplus_train": to_column(iplus[train_mask]),
        "iminus_train": to_column(iminus[train_mask]),
        "x_holdout": to_matrix(features[holdout_mask]),
        "iplus_holdout": to_column(iplus[holdout_mask]),
        "iminus_holdout": to_column(iminus[holdout_mask]),
    }


def build_bin_datasets(
    arrays: Dict[str, Any],
    validation_fraction: float,
) -> Tuple[data.TensorDataset, data.TensorDataset, data.TensorDataset, Dict[str, torch.Tensor]]:

    x_train = arrays["x_train"]
    iplus_train = arrays["iplus_train"]
    iminus_train = arrays["iminus_train"]
    x_holdout = arrays["x_holdout"]
    iplus_holdout = arrays["iplus_holdout"]
    iminus_holdout = arrays["iminus_holdout"]

    x_mean = x_train.mean(dim=0, keepdim=True)
    x_std = x_train.std(dim=0, keepdim=True)

    iplus_mean = iplus_train.mean()
    iplus_std = iplus_train.std()

    iminus_mean = iminus_train.mean()
    iminus_std = iminus_train.std()

    x_train_norm = (x_train - x_mean) / x_std
    iplus_train_norm = (iplus_train - iplus_mean) / iplus_std
    iminus_train_norm = (iminus_train - iminus_mean) / iminus_std

    x_holdout_norm = (x_holdout - x_mean) / x_std
    iplus_holdout_norm = (iplus_holdout - iplus_mean) / iplus_std
    iminus_holdout_norm = (iminus_holdout - iminus_mean) / iminus_std

    split_source = data.TensorDataset(
        x_holdout_norm, iplus_holdout_norm, iminus_holdout_norm
    )
    val_count = int(round(len(split_source) * validation_fraction))
    val_count = max(1, min(val_count, len(split_source) - 1))
    test_count = len(split_source) - val_count
    val_dataset, test_dataset = data.random_split(
        split_source,
        [val_count, test_count],
    )

    train_dataset = data.TensorDataset(
        x_train_norm,
        iplus_train_norm,
        iminus_train_norm,
    )

    val_indices = val_dataset.indices
    test_indices = test_dataset.indices

    val_bin_dataset = data.TensorDataset(
        x_holdout_norm[val_indices],
        iplus_holdout_norm[val_indices],
        iminus_holdout_norm[val_indices],
    )
    test_bin_dataset = data.TensorDataset(
        x_holdout_norm[test_indices],
        iplus_holdout_norm[test_indices],
        iminus_holdout_norm[test_indices],
    )

    stats = {
        "x_mean": x_mean.detach().cpu(),
        "x_std": x_std.detach().cpu(),
        "iplus_mean": iplus_mean.detach().cpu(),
        "iplus_std": iplus_std.detach().cpu(),
        "iminus_mean": iminus_mean.detach().cpu(),
        "iminus_std": iminus_std.detach().cpu(),
    }
    return train_dataset, val_bin_dataset, test_bin_dataset, stats


def clone_state_dict(model: nn.Module) -> Dict[str, torch.Tensor]:
    return {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}


def train_model(
    train_dataset: data.TensorDataset,
    val_dataset: data.TensorDataset,
    args: argparse.Namespace,
    device: torch.device = DEVICE,
) -> Tuple[nn.Module, float]:
    train_loader = data.DataLoader(
        train_dataset, batch_size=BATCH_SIZE, shuffle=True
    )
    val_loader = data.DataLoader(
        val_dataset, batch_size=BATCH_SIZE, shuffle=False
    )

    model = BinModel(
        input_dim=train_dataset.tensors[0].shape[1],
        hidden_dim=HIDDEN_DIM,
    ).to(device)

    best_val_loss = float("inf")
    best_model_state = None

    optimizer = optim.AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=LR_FACTOR,
        patience=LR_PATIENCE,
        min_lr=LR_MIN,
    )
    loss_fn = nn.L1Loss()
    epochs_without_improvement = 0

    for epoch in range(NUM_EPOCHS):
        model.train()
        train_loss_sum = 0.0
        train_batches = 0
        for x_batch, y_iplus, y_iminus in train_loader:
            x_batch = x_batch.to(device)
            y_iplus = y_iplus.squeeze(-1).to(device)
            y_iminus = y_iminus.squeeze(-1).to(device)

            pred_iplus, pred_iminus = model(x_batch)
            loss = loss_fn(pred_iplus, y_iplus) + loss_fn(pred_iminus, y_iminus)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
            optimizer.step()

            train_loss_sum += loss.item()
            train_batches += 1

        avg_train_loss = train_loss_sum / max(train_batches, 1)

        model.eval()
        val_loss_sum = 0.0
        val_batches = 0
        with torch.no_grad():
            for x_val, y_iplus_val, y_iminus_val in val_loader:
                x_val = x_val.to(device)
                y_iplus_val = y_iplus_val.squeeze(-1).to(device)
                y_iminus_val = y_iminus_val.squeeze(-1).to(device)

                pred_iplus_val, pred_iminus_val = model(x_val)
                val_loss = loss_fn(pred_iplus_val, y_iplus_val) + loss_fn(
                    pred_iminus_val, y_iminus_val
                )
                val_loss_sum += val_loss.item()
                val_batches += 1

        avg_val_loss = val_loss_sum / max(val_batches, 1)
        scheduler.step(avg_val_loss)

        if best_model_state is None or avg_val_loss < best_val_loss - MIN_DELTA:
            best_val_loss = avg_val_loss
            best_model_state = clone_state_dict(model)
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        if epoch % 50 == 0 or epoch == NUM_EPOCHS - 1:
            current_lr = optimizer.param_groups[0]["lr"]
            print(
                f"Bin {args.bin_idx} | epoch {epoch:04d} | "
                f"train {avg_train_loss:.6f} | val {avg_val_loss:.6f} | "
                f"lr {current_lr:.2e}",
                flush=True,
            )

        if epochs_without_improvement >= PATIENCE:
            print(
                f"Stopping early at epoch {epoch} (best val {best_val_loss:.6f})",
                flush=True,
            )
            break

    if best_model_state is not None:
        model.load_state_dict(best_model_state)

    return model, best_val_loss


def evaluate_model(
    model: nn.Module,
    test_dataset: data.TensorDataset,
    stats: Dict[str, torch.Tensor],
    args: argparse.Namespace,
    device: torch.device,
) -> Dict[str, float]:
    test_loader = data.DataLoader(test_dataset, batch_size=1024, shuffle=False)
    loss_fn = nn.L1Loss()

    pred_iplus_batches = []
    pred_iminus_batches = []
    true_iplus_batches = []
    true_iminus_batches = []
    test_loss_sum = 0.0
    test_batches = 0

    model.eval()
    with torch.no_grad():
        for x_test, y_iplus, y_iminus in test_loader:
            x_test = x_test.to(device)
            y_iplus = y_iplus.squeeze(-1).to(device)
            y_iminus = y_iminus.squeeze(-1).to(device)

            pred_iplus, pred_iminus = model(x_test)
            test_loss = loss_fn(pred_iplus, y_iplus) + loss_fn(pred_iminus, y_iminus)

            pred_iplus_batches.append(pred_iplus.cpu())
            pred_iminus_batches.append(pred_iminus.cpu())
            true_iplus_batches.append(y_iplus.cpu())
            true_iminus_batches.append(y_iminus.cpu())
            test_loss_sum += test_loss.item()
            test_batches += 1

    pred_iplus_norm = torch.cat(pred_iplus_batches).numpy()
    pred_iminus_norm = torch.cat(pred_iminus_batches).numpy()
    true_iplus_norm = torch.cat(true_iplus_batches).numpy()
    true_iminus_norm = torch.cat(true_iminus_batches).numpy()

    iplus_mean = float(stats["iplus_mean"].item())
    iplus_std = float(stats["iplus_std"].item())
    iminus_mean = float(stats["iminus_mean"].item())
    iminus_std = float(stats["iminus_std"].item())

    pred_iplus = pred_iplus_norm * iplus_std + iplus_mean
    pred_iminus = pred_iminus_norm * iminus_std + iminus_mean
    true_iplus = true_iplus_norm * iplus_std + iplus_mean
    true_iminus = true_iminus_norm * iminus_std + iminus_mean

    ss_res_iplus = np.sum((true_iplus - pred_iplus) ** 2)
    ss_tot_iplus = np.sum((true_iplus - np.mean(true_iplus)) ** 2)
    ss_res_iminus = np.sum((true_iminus - pred_iminus) ** 2)
    ss_tot_iminus = np.sum((true_iminus - np.mean(true_iminus)) ** 2)

    rpe_iplus = np.zeros_like(true_iplus)
    rpe_iminus = np.zeros_like(true_iminus)
    mask_iplus = np.abs(true_iplus) > 1e-10
    mask_iminus = np.abs(true_iminus) > 1e-10
    rpe_iplus[mask_iplus] = (
        np.abs(pred_iplus[mask_iplus] - true_iplus[mask_iplus])
        / np.abs(true_iplus[mask_iplus])
        * 100.0
    )
    rpe_iminus[mask_iminus] = (
        np.abs(pred_iminus[mask_iminus] - true_iminus[mask_iminus])
        / np.abs(true_iminus[mask_iminus])
        * 100.0
    )

    return {
        "test_l1_loss": test_loss_sum / max(test_batches, 1),
        "r2_iplus": 1.0 - float(ss_res_iplus / (ss_tot_iplus + 1e-12)),
        "r2_iminus": 1.0 - float(ss_res_iminus / (ss_tot_iminus + 1e-12)),
        "median_rpe_iplus": float(np.median(rpe_iplus[mask_iplus])) if np.any(mask_iplus) else 0.0,
        "median_rpe_iminus": float(np.median(rpe_iminus[mask_iminus])) if np.any(mask_iminus) else 0.0,
    }


def save_outputs(
    args: argparse.Namespace,
    model: nn.Module,
    best_val_loss: float,
    stats: Dict[str, torch.Tensor],
    metrics: Dict[str, float],
    model_path: Path,
    metrics_path: Path,
) -> None:
    payload = {
        "model_state_dict": model.state_dict(),
        "best_val_loss": best_val_loss,
        "X_mean": stats["x_mean"].numpy(),
        "X_std": stats["x_std"].numpy(),
        "Iplus_mean": float(stats["iplus_mean"].item()),
        "Iplus_std": float(stats["iplus_std"].item()),
        "Iminus_mean": float(stats["iminus_mean"].item()),
        "Iminus_std": float(stats["iminus_std"].item()),
        "bin_idx": args.bin_idx,
        "hidden_dim": HIDDEN_DIM,
        "metrics": metrics,
        "args": vars(args),
    }
    torch.save(payload, model_path)

    metrics_payload = {
        "bin_idx": args.bin_idx,
         "model": str(model_path),
        "best_val_loss": best_val_loss,
        **metrics,
    }
    metrics_path.write_text(json.dumps(metrics_payload, indent=2) + "\n")


def main() -> None:
    args = parse_args()

    model_path = args.output_dir / f"binning_model_bin_{args.bin_idx}.pth"
    metrics_path = args.output_dir / f"binning_model_bin_{args.bin_idx}_metrics.json"
    args.output_dir.mkdir(parents=True, exist_ok=True)

    torch.cuda.manual_seed_all(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)

    arrays = load_burn_bin_arrays(
        lookup_path=args.lookup_table,
        target_bin=args.bin_idx,
        train_polarization_fraction=TRAIN_POLARIZATION_FRACTION,
    )
    train_dataset, val_dataset, test_dataset, stats = build_bin_datasets(
        arrays=arrays,
        validation_fraction=TRAIN_POLARIZATION_FRACTION
    )

    model, best_val_loss = train_model(
        train_dataset=train_dataset,
        val_dataset=val_dataset,
        args=args,
    )
    metrics = evaluate_model(
        model=model,
        test_dataset=test_dataset,
        stats=stats,
        args=args,
    )
    save_outputs(
        args=args,
        model=model,
        best_val_loss=best_val_loss,
        stats=stats,
        metrics=metrics,
        model_path=model_path,
        metrics_path=metrics_path,
    )

    print(f"Saved model to {model_path}", flush=True)
    print(f"Saved metrics to {metrics_path}", flush=True)
    print(
        " | ".join(
            [
                f"best_val={best_val_loss:.6f}",
                f"test_l1={metrics['test_l1_loss']:.6f}",
                f"r2_iplus={metrics['r2_iplus']:.6f}",
                f"r2_iminus={metrics['r2_iminus']:.6f}",
            ]
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()